/* generated by src/scripts/generate-create-path.ts */

type WithoutParams = '/about' | '/' | '/thoughts';
type WithParams = {
	'/thoughts/[slug]': { slug: string };
};

export function createPath<T extends WithoutParams>(path: T): string;
export function createPath<T extends keyof WithParams>(
	path: T,
	params: WithParams[T],
): string;
export function createPath(p: string, params?: Record<string, string>): string {
	if (!params) return p;
	let result = p;
	for (const [key, value] of Object.entries(params)) {
		result = result.replace(`[${key}]`, value);
	}
	return result;
}
